# Generated by Django 3.2.9 on 2021-11-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='label',
        ),
        migrations.AddField(
            model_name='game',
            name='gameCategories',
            field=models.ManyToManyField(related_name='gameCategory', through='gamerraterapi.GameCategory', to='gamerraterapi.Category'),
        ),
    ]
