# Generated by Django 3.2.9 on 2021-11-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0002_auto_20211105_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameCategories',
            field=models.ManyToManyField(related_name='categories', through='gamerraterapi.GameCategory', to='gamerraterapi.Category'),
        ),
    ]
