# Generated by Django 3.2.9 on 2021-11-05 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0003_alter_game_gamecategories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gameCategories',
            new_name='categories',
        ),
    ]
