# Generated by Django 3.2.9 on 2021-11-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0004_rename_gamecategories_game_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='url',
        ),
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(null=True, upload_to='gameimages/'),
        ),
    ]
